### ISSUE TITLE
[PE-D][Tester D] Light/Dark mode and sensitive info toggle buttons do not contrast with dark mode on low brightness

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F11-3/tp#110]
Hi! I believe this is an a11y bug, as some users will prefer to use their devices on low brightness, especially in dim conditions or with eye issues. I would recommend changing the button colors to white on dark mode.

**Steps to reproduce**
- Start application.
- Lower screen brightness.
- Ensure you are on dark mode and check for the contrast level on the toggle buttons.

**Expected**
- High contrast

**Actual**
- Low contrast

![Screenshot 2022-10-28 at 4.24.26 PM.png](https://raw.githubusercontent.com/kxrt/ped/main/files/15471508-e1ef-4c47-ab0f-a5d586510e05.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: kxrt/ped#2

**Comment by jovitaanderson** [comment]
Issue considered as UI enhancement. Not allowed in v1.4.
