### ISSUE TITLE
[PE-D][Tester B] Total number of clients counter not updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F11-3/tp#133]
After deleting all clients, client counter does not update to zero
![Screenshot 2022-10-28 at 4.53.00 PM.png](https://raw.githubusercontent.com/SilasTSL/ped/main/files/31a2e522-73a2-41ba-a20d-a3eb955db5f3.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: SilasTSL/ped#8

**Comment by jovitaanderson** [comment]
Fixed by PR: #167
