### ISSUE TITLE
[PE-D][Tester A] Lock command accepts multiple parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F11-3/tp#158]
Lock command accepts multiple parameters, ignoring parameters after the first one and simply behaving as it the command was "lock"

![image.png](https://raw.githubusercontent.com/ALWHgithub/ped/main/files/ad6c1f11-500b-4797-89ee-31f8b39f087b.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ALWHgithub/ped#12

**Comment by leecaregene** [comment]
Intentional feature, not fixing.
