### ISSUE TITLE
[PE-D][Tester D] Application cannot startup if there are no clients stored

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F11-3/tp#161]
The application reports a "Fatal error during initialising", and cannot start up at all until `addressbook.json` is deleted or repopulated with proper data. On repeated attempts to start the application up, the same error persists.

**Steps to reproduce**
- Start up the application.
- Execute `delete all`.
  - Alternatively, head to `data/addressbook.json` and save the following: `{
  "persons" : []
}`
- Exit the application.
- Attempt to start the application again.

**Expected**
- Application starts with empty client list and portfolio window.

**Actual**
- Application fails to start.
- Error window opens up.

![Startup error](https://raw.githubusercontent.com/kxrt/ped/main/files/686daccb-9c52-4ed8-95fb-d0fbf7d99d4b.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: kxrt/ped#11

**Comment by jovitaanderson** [comment]
Fixed by PR: #167
